import { Product } from './googleSheets';

export interface CartItem extends Product {
    quantity: number;
}

export interface CustomerDetails {
    name: string;
    address?: string;
}

export function generateWhatsAppLink(
    phoneNumber: string,
    cart: CartItem[],
    customer?: CustomerDetails
): string {
    if (!phoneNumber || cart.length === 0) return '';

    // sanitize phone number: remove +, spaces, dashes
    const cleanPhone = phoneNumber.replace(/[^0-9]/g, '');

    let message = `*New Order from QRCart.link*\n\n`;

    if (customer?.name) {
        message += `*Customer:* ${customer.name}\n`;
    }
    if (customer?.address) {
        message += `*Address:* ${customer.address}\n`;
    }

    message += `\n*Items:*\n`;

    let total = 0;
    cart.forEach(item => {
        const itemTotal = item.price * item.quantity;
        message += `• ${item.quantity}x ${item.name} ($${item.price.toFixed(2)})\n`;
        total += itemTotal;
    });

    message += `\n*Total Amount: $${total.toFixed(2)}*\n\n`;
    message += `Generated by QRCart.link`;

    return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(message)}`;
}
